sudo: true
dist: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a usertestingapp
- sfdx force:source:push -u usertestingapp
- sfdx force:apex:test:run -u usertestingapp -c -r human
- sfdx force:org:delete -u usertestingapp -p
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a deployorg
- sfdx force:user:password:generate
- sfdx force:org:display
- mkdir mdapioutputdir
- sfdx force:source:convert -d mdapioutputdir/
- sfdx force:mdapi:deploy -d mdapioutputdir/ -u deployorg
